<?php include __DIR__ . '/../header.phtml'; ?>

    <div class="col-md-12">
    <h1 class="users-header"><?=$title; ?><?php if (isset($roleId) && isset($roles) && isset($roles[$roleId])): ?> : <?=$roles[$roleId]; ?><?php endif; ?></h1>
    <nav id="sub-nav">
        <nav><a class="btn-sm btn-info" href="/users/add<?php if (isset($roleId) && (null !== $roleId)): ?><?='/' . $roleId; ?><?php endif; ?>">+ Add</a></nav>
        <nav><a class="btn-sm btn-info" href="/users">Back</a></nav>
    </nav>
<?php if (isset($form)): ?>
<?=$form; ?>
<?php else: ?>
    <form id="role-select-form" action="/users/add" method="get">
        <div><h3>Select Role</h3></div>
        <div>
            <select name="role_id" id="role_id" data-user="add" class="pop-select">
                <option value="0">----</option>
<?php foreach ($roles as $role): ?>
                <option value="<?=$role->id; ?>"><?=$role->name; ?></option>
<?php endforeach; ?>
            </select>
        </div>
    </form>
<?php endif; ?>
    </div>

<?php include __DIR__ . '/../footer.phtml'; ?>
