<?php include __DIR__ . '/../header.phtml'; ?>
    <h1><?=$title; ?> : <span id="title-span"><?=$username; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role_name, BASE_PATH . APP_URI . '/users/add[/]')): ?>
        <nav><a href="<?=BASE_PATH . APP_URI . '/users/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=BASE_PATH . APP_URI . '/users'; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include __DIR__ . '/../footer.phtml'; ?>
