<?php include __DIR__ . '/../header.phtml'; ?>

    <div class="col-md-12">
    <h1 class="users-header"><?=$title; ?> : <span id="title-span"><?=$username; ?></span></h1>
<?php if (null !== $last_login): ?>
    <div class="pull-right text-right small gray" style="margin-top: 10px;">
        <strong>Last Login:</strong> <?=date('M j Y g:i A', strtotime($last_login)); ?> [<?=$last_ip; ?>]
    </div>
<?php endif; ?>
    <nav id="sub-nav">
        <nav><a class="btn-sm btn-info" href="<?=BASE_PATH . APP_URI; ?>/users/add/<?php if (isset($roleId) && (null !== $roleId)): ?><?=$roleId; ?><?php endif; ?>">+ Add</a></nav>
        <nav><a class="btn-sm btn-info" href="<?=BASE_PATH . APP_URI; ?>/users">Back</a></nav>
    </nav>
<?=$form; ?>
    </div>

<?php include __DIR__ . '/../footer.phtml'; ?>
