<?php include $phireHeader; ?>
    <h1><?=$title; ?></h1>
<?php if (count($users) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'users', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=BASE_PATH . APP_URI . '/users/add'; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'users', 'remove')): ?>
    <form id="users-form" action="<?=BASE_PATH . APP_URI . '/users/remove'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=id';?>">#</a></th>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=username';?>">Username</a></th>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=email';?>">Email</a></th>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=role_name';?>">Role</a></th>
                <th class="text-center">Edit</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'users', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_users" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($users as $u): ?>
            <tr>
                <td><?=$u->id; ?></td>
                <td><?=$u->username; ?></td>
                <td><?=$u->email; ?></td>
                <td><?=(!empty($u->role_name) ? $u->role_name : '[Blocked]'); ?></td>
                <td><?php if ($acl->isAllowed($user->role, 'users', 'edit')): ?><a class="edit-link" href="<?=BASE_PATH . APP_URI . '/users/edit/' . $u->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($user->id != $u->id) && ($acl->isAllowed($user->role, 'users', 'remove'))): ?><input type="checkbox" name="rm_users[]" id="rm_users<?=$i++; ?>" value="<?=$u->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'users', 'remove')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Remove" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'users', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=BASE_PATH . APP_URI . '/users/add'; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no users.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
