<?php include __DIR__ . '/../header.phtml'; ?>
    <h1><?=$title; ?></h1>
<?php if (count($users) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
    <p><a href="<?=BASE_PATH . APP_URI . '/users/add'; ?>">+ Add</a></p>
    <form id="users-form" action="<?=BASE_PATH . APP_URI . '/users/remove'; ?>" method="post">
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=id';?>">#</a></th>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=username';?>">Username</a></th>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=email';?>">Email</a></th>
                <th><a href="<?=BASE_PATH . APP_URI . '/users?sort=role_name';?>">Role</a></th>
                <th>Edit</th>
                <th><input type="checkbox" name="checkall" id="checkall" value="rm_users" /></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($users as $u): ?>
            <tr>
                <td><?=$u->id; ?></td>
                <td><?=$u->username; ?></td>
                <td><?=$u->email; ?></td>
                <td><?=(!empty($u->role_name) ? $u->role_name : '[Blocked]'); ?></td>
                <td><?php if ($acl->isAllowed($user->role_name, BASE_PATH . APP_URI . '/users/edit/:id')): ?><a href="<?=BASE_PATH . APP_URI . '/users/edit/' . $u->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td><?php if ($user->id != $u->id): ?><input type="checkbox" name="rm_users[]" id="rm_users<?=$i++; ?>" value="<?=$u->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php endforeach; ?>
        </table>
        <div><input type="submit" name="submit" value="Remove" /></div>
    </form>
<?php else: ?>
    <p>There are currently no users.</p>
<?php endif; ?>
<?php include __DIR__ . '/../footer.phtml'; ?>
