<?php include $phireHeader; ?>
    <h1 class="users-header"><?=$title; ?> : <span id="title-span"><?=$role_name; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'roles', 'add')): ?>
            <nav><a href="<?=$phireUri . '/users/roles/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/users/roles'; ?>">Back</a></nav>
    </nav>
<?=$form; ?>
<?php include $phireFooter; ?>
