<?php include $phireHeader; ?>
    <h1 class="modules-header"><?=$title; ?></h1>
<?php if (($newModules > 0) && ($acl->isAllowed($user->role, 'modules', 'install'))): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri . '/modules/install'; ?>">Install (<?=$newModules; ?>)</a></nav>
    </nav>
<?php endif; ?>
<?php if (count($modules) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?>
    <form id="modules-form" action="<?=$phireUri . '/modules/process'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/modules?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/modules?sort=folder';?>">Name</a></th>
                <th>Version</th>
                <th>Description</th>
                <th>Author</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><a href="<?=$phireUri . '/modules?sort=active';?>">Active</a><?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><a href="<?=$phireUri . '/modules?sort=order';?>">Order</a><?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_modules" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($modules as $module): ?>
<?php
    $assets  = unserialize($module->assets);
    $yesChecked = ($module->active)  ? ' checked="checked"' : null;
    $noChecked  = (!$module->active) ? ' checked="checked"' : null;
?>
            <tr>
                <td><?=$module->id; ?></td>
                <td><?=($assets['info']['Module Name']) ? $assets['info']['Module Name'] : '&nbsp;'; ?></td>
                <td><?=$module->version; ?></td>
                <td><?=($assets['info']['Description']) ? $assets['info']['Description'] : '&nbsp;'; ?></td>
                <td><?=($assets['info']['Author']) ? $assets['info']['Author'] : '&nbsp;'; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="radio" name="active_<?=$module->id; ?>" value="1" <?=$yesChecked; ?>/> Yes &nbsp;&nbsp;&nbsp; <input type="radio" name="active_<?=$module->id; ?>" value="0" <?=$noChecked; ?>/> No<?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="text" name="order_<?=$module->id; ?>" value="<?=(int)$module->order; ?>" class="module-order" size="2" /> <?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="checkbox" name="rm_modules[]" id="rm_modules<?=$i++; ?>" value="<?=$module->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php if (null !== $module->nav): ?>
            <tr class="no-background no-padding">
                <td colspan="8" class="no-background no-padding">
<?=$module->nav; ?>
                </td>
            </tr>
<?php endif; ?>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Process" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <p>There are currently no modules.<?php if (($newModules > 0) && ($acl->isAllowed($user->role, 'modules', 'install'))): ?> New modules have been detected. Click the install button above to install them.<?php endif; ?></p>
<?php endif; ?>
<?php include $phireFooter; ?>
