<?php include $phireHeader; ?>
        <h1 class="update-header"><?=$title; ?></h1>
        <h3>You have chosen to update the <strong><?=$module_name; ?></strong> module to version <strong class="required"><?=$module_update_version; ?></strong></h3>
        <p class="warning">Please back up all of your files and your database before proceeding.</p>
        <a class="update-btn" href="<?=$phireUri; ?>/modules/update/<?=$module_id;?>?update=1">Update</a>
<?php include $phireFooter; ?>
