<?php include __DIR__ . '/../header.phtml'; ?>

        <div class="col-md-12">
        <h1 class="config-header"><?=$title; ?></h1>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th colspan="2">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><strong>Version</strong></td>
                    <td><?=$phireVersion; ?></td>
                </tr>
                <tr>
                    <td><strong>Domain</strong></td>
                    <td><?=(isset($_SERVER['HTTP_HOST'])) ? $_SERVER['HTTP_HOST'] : 'N/A'; ?></td>
                </tr>
                <tr>
                    <td><strong>Document Root</strong></td>
                    <td><?=(isset($_SERVER['DOCUMENT_ROOT'])) ? $_SERVER['DOCUMENT_ROOT'] : 'N/A'; ?></td>
                </tr>
                <tr>
                    <td><strong>Operating System</strong></td>
                    <td><?=PHP_OS; ?></td>
                </tr>
                <tr>
                    <td><strong>Server Software</strong></td>
                    <td><?=(isset($_SERVER['SERVER_SOFTWARE'])) ? $_SERVER['SERVER_SOFTWARE'] : 'N/A'; ?></td>
                </tr>
                <tr>
                    <td><strong>Database</strong></td>
                    <td><?=$database; ?> (<?=$dbVersion; ?>)</td>
                </tr>
                <tr>
                    <td><strong>PHP</strong></td>
                    <td><?=PHP_VERSION; ?></td>
                </tr>
                <tr>
                    <td><strong>Installed On</strong></td>
                    <td><?=(!empty($installed_on)) ? date('M j Y g:i A', strtotime($installed_on)) : 'N/A'; ?></td>
                </tr>
                <tr>
                    <td><strong>Updated On</strong></td>
                    <td><?=(!empty($updated_on)) ? date('M j Y g:i A', strtotime($updated_on)) : 'N/A'; ?></td>
                </tr>
            </tbody>
        </table>
        </div>

<?php include __DIR__ . '/../footer.phtml'; ?>