<?php include __DIR__ . '/../header.phtml'; ?>
    <h1><?=$title; ?></h1>
    <form id="config-form" method="post" action="<?=BASE_PATH . APP_URI; ?>/config">
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr><th colspan="2">&nbsp;</th></tr>
<?php foreach($overview as $setting => $value): ?>
            <tr>
                <td style="width: 25%;"><strong><?=ucwords(str_replace(['_', 'php'], [' ', 'PHP'], $setting)); ?></strong></td><td><?=(!empty($value) ? $value : '&nbsp;'); ?></td>
            </tr>
<?php endforeach; ?>
            <tr><th colspan="2">&nbsp;</th></tr>
            <tr class="no-background">
                <td class="no-background">
                    <strong>Date &amp; Time Format</strong>
                </td>
                <td class="no-background">
<?php
$wasChecked = false;
foreach($config['datetime_formats'] as $datetime):
    if ($config['datetime_format'] == $datetime):
        $checked    = 'checked="checked" ';
        $wasChecked = true;
    else:
        $checked = '';
    endif;
?>
                    <div><input type="radio" name="datetime_format" id="datetime_format" onclick="phire.customDatetime('<?=BASE_PATH . APP_URI; ?>');" <?=$checked; ?>value="<?=$datetime; ?>" /> <span class="radio-block-span"><?=date($datetime); ?></span></div>
<?php endforeach; ?>
                    <div>
                        <input type="radio" name="datetime_format" id="datetime_format8" onclick="phire.customDatetime('<?=BASE_PATH . APP_URI; ?>');" <?=((!$wasChecked) ? 'checked="checked" ' : ''); ?>value="<?=((!$wasChecked) ? $config['datetime_format'] : ''); ?>" />
                        <input type="text" name="datetime_format_custom" id="datetime_format_custom" onkeyup="phire.customDatetime('<?=BASE_PATH . APP_URI; ?>')" value="<?=((!$wasChecked) ? $config['datetime_format'] : ''); ?>" size="10" />
                        <span id="datetime-custom"><?=((!$wasChecked) ? '(' . date($config['datetime_format']) . ')' : ''); ?></span>
                    </div>
                </td>
            </tr>
            <tr class="no-background">
                <td class="no-background">
                    <strong>Pagination</strong>
                </td>
                <td class="no-background">
                    <input type="text" name="pagination" id="pagination" size="5" value="<?=$config['pagination']; ?>" />
                </td>
            </tr>
            <tr class="no-background">
                <td class="no-background">
                    <strong>Force SSL</strong>
                </td>
                <td class="no-background">
                    <input type="radio" name="force_ssl" id="force_ssl" value="1" <?=(($config['force_ssl']) ? 'checked="checked" ' : null); ?>/> Yes &nbsp;&nbsp;&nbsp; <input type="radio" name="force_ssl" id="force_ssl" value="0" <?=((!$config['force_ssl']) ? 'checked="checked" ' : null); ?>/> No
                </td>
            </tr>
        </table>
        <div><input type="submit" name="submit" value="Save" /></div>
    </form>
<?php include __DIR__ . '/../footer.phtml'; ?>
