<?php include __DIR__ . '/../header.phtml'; ?>

    <div class="col-md-12">
    <h1 class="roles-header"><?=$title; ?></span></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'roles', 'add')): ?>
        <nav><a class="btn-sm btn-info" href="<?=BASE_PATH . APP_URI; ?>/roles/add">+ Add</a></nav>
<?php endif; ?>
        <nav><a class="btn-sm btn-info" href="<?=BASE_PATH . APP_URI; ?>/roles">Back</a></nav>
    </nav>
<?=$form; ?>
    </div>

<?php include __DIR__ . '/../footer.phtml'; ?>


