<?php include __DIR__ . '/../header.phtml'; ?>

        <div class="col-md-12">
        <h1 class="roles-header"><?=$title; ?></h1>
<?php if (null !== $pages): ?>
        <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'roles', 'add')): ?>
        <nav id="sub-nav">
            <nav><a class="btn-sm btn-info" href="<?=BASE_PATH . APP_URI; ?>/roles/add">+ Add</a></nav>
        </nav>
<?php endif; ?>
        <div class="table-responsive">
<?php if ($acl->isAllowed($user->role, 'roles', 'remove')): ?>
            <form id="roles-form" action="<?=BASE_PATH . APP_URI; ?>/roles/remove" method="post">
<?php endif; ?>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th class="col-md-1 text-center"><a href="<?=BASE_PATH . APP_URI; ?>/roles?sort=id<?=(($queryString != '') ? '&' . $queryString : '');?>">#</a></th>
                    <th><a href="<?=BASE_PATH . APP_URI; ?>/roles?sort=name<?=(($queryString != '') ? '&' . $queryString : '');?>">Name</a></th>
                    <th class="text-center"><?php if ($acl->isAllowed($user->role, 'roles', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                    <th class="col-md-1 text-center"><?php if ($acl->isAllowed($user->role, 'roles', 'remove')): ?><input type="checkbox" name="check_all" id="checkAll" data-name="rm_roles" value="" /><?php else: ?>&nbsp;<?php endif; ?></th>
                </tr>
                </thead>
                <tbody>
<?php foreach ($roles as $role): ?>
                <tr>
                    <td class="text-center"><?=$role->id; ?></td>
                    <td><?=$role->name; ?></td>
                    <td class="text-center"><?php if (($acl->isAllowed($user->role, 'roles', 'edit')) && ($acl->isAllowed($user->role, 'role-' . $role->id, 'edit'))): ?><a class="edit-link" href="<?=BASE_PATH . APP_URI; ?>/roles/edit/<?=$role->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                    <td class="text-center"><?php if (($user->role_id != $role->id) && ($acl->isAllowed($user->role, 'roles', 'remove')) && ($acl->isAllowed($user->role, 'role-' . $role->id, 'remove'))): ?><input type="checkbox" name="rm_roles[]" value="<?=$role->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
                </tr>
<?php endforeach; ?>
                </tbody>
            </table>
<?php if ($acl->isAllowed($user->role, 'roles', 'remove')): ?>
            <div id="form-footer">
                <input type="submit" name="submit" class="btn btn-md btn-primary text-uppercase" value="Process" />
            </div>
            </form>
<?php endif; ?>
        </div>
        </div>

<?php include __DIR__ . '/../footer.phtml'; ?>