<?php include $phireHeader; ?>
    <h1 class="modules-header"><?=$title; ?></h1>
<?php if (($newModules > 0) && ($acl->isAllowed($user->role, 'modules', 'install'))): ?>
    <nav id="sub-nav">
        <nav><a href="<?=BASE_PATH . APP_URI . '/modules/install'; ?>">Install (<?=$newModules; ?>)</a>(New modules detected.)</nav>
    </nav>
<?php endif; ?>
<?php if (count($modules) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?>
    <form id="modules-form" action="<?=BASE_PATH . APP_URI . '/modules/process'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=BASE_PATH . APP_URI . '/modules?sort=id';?>">#</a></th>
                <th>Name</th>
                <th>Version</th>
                <th>Description</th>
                <th>Author</th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><a href="<?=BASE_PATH . APP_URI . '/modules?sort=active';?>">Active</a><?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="checkbox" name="checkall" id="checkall" value="rm_modules" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($modules as $module): ?>
<?php
    $assets  = unserialize($module->assets);
    $yesChecked = ($module->active)  ? ' checked="checked"' : null;
    $noChecked  = (!$module->active) ? ' checked="checked"' : null;
?>
            <tr>
                <td><?=$module->id; ?></td>
                <td><?=($assets['info']['Module Name']) ? $assets['info']['Module Name'] : '&nbsp;'; ?></td>
                <td><?=($assets['info']['Version']) ? $assets['info']['Version'] : '&nbsp;'; ?></td>
                <td><?=($assets['info']['Description']) ? $assets['info']['Description'] : '&nbsp;'; ?></td>
                <td><?=($assets['info']['Author']) ? $assets['info']['Author'] : '&nbsp;'; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="radio" name="active_<?=$module->id; ?>" value="1" <?=$yesChecked; ?>/> Yes &nbsp;&nbsp;&nbsp; <input type="radio" name="active_<?=$module->id; ?>" value="0" <?=$noChecked; ?>/> No<?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?><input type="checkbox" name="rm_modules[]" id="rm_modules<?=$i++; ?>" value="<?=$module->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
            </tr>
<?php if (null !== $module->nav): ?>
            <tr class="no-background no-padding">
                <td colspan="7" class="no-background no-padding">
<?=$module->nav; ?>
                </td>
            </tr>
<?php endif; ?>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'modules', 'process')): ?>
        <div id="form-footer"><input type="submit" name="submit" class="process-btn" value="Process" /></div>
    </form>
<?php endif; ?>
<?php else: ?>
    <p>There are currently no modules.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
