<?php include __DIR__ . '/header.phtml'; ?>
    <h1><?=$title; ?></h1>
    <form id="config-form" method="post" action="<?=BASE_PATH . APP_URI; ?>/config">
        <table cellpadding="0" cellspacing="0" border="0">
            <tr><th colspan="2">&nbsp;</th></tr>
<?php foreach($overview as $setting => $value): ?>
            <tr>
                <td><strong><?=ucwords(str_replace(['_', 'php'], [' ', 'PHP'], $setting)); ?></strong></td><td><?=$value; ?></td>
            </tr>
<?php endforeach; ?>
            <tr><th colspan="2">&nbsp;</th></tr>
            <tr>
                <td>
                    <strong>Date &amp; Time Format</strong>
                </td>
                <td>
<?php
$wasChecked = false;
foreach($config['datetime_formats'] as $datetime):
    if ($config['datetime_format'] == $datetime):
        $checked    = 'checked="checked" ';
        $wasChecked = true;
    else:
        $checked = '';
    endif;
?>
                    <div><input type="radio" name="datetime_format" id="datetime_format" <?=$checked; ?>value="<?=$datetime; ?>" /> <span class="radio-block-span"><?=date($datetime); ?></span></div>
<?php endforeach; ?>
                    <div><input type="radio" name="datetime_format" id="datetime_format8" <?=((!$wasChecked) ? 'checked="checked" ' : ''); ?>value="<?=((!$wasChecked) ? $config['datetime_format'] : ''); ?>" /> <input type="text" name="datetime_format_custom" id="datetime_format_custom" value="<?=((!$wasChecked) ? $config['datetime_format'] : ''); ?>" size="10" /> <span id="datetime-custom"><?=((!$wasChecked) ? date($config['datetime_format']) : ''); ?></span></div>
                </td>
            </tr>
            <tr><th colspan="2">&nbsp;</th></tr>
            <tr>
                <td>
                    <strong>Pagination</strong>
                </td>
                <td>
                    <input type="text" name="pagination" id="pagination" size="5" value="<?=$config['pagination']; ?>" />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" name="submit" value="Save" />
                </td>
            </tr>
        </table>
    </form>
<?php include __DIR__ . '/footer.phtml'; ?>
