<?php if (isset($fluidNav)): ?>
            </div>
        </div>
    </div>
<?php endif; ?>
    </div>
<!-- Footer //-->
    <footer class="footer">
        <div class="text-muted"><?=$application_title; ?> &copy; 2009-<?=date('Y'); ?> <a href="http://www.nolainteractive.com/" target="_blank">NOLA Interactive, LLC</a>. All Rights Reserved.</div>
    </footer>
    <div id="saved" class="alert alert-success" role="alert"<?=(isset($saved) ? ' data-saved="1"' : null); ?>>Saved</div>
    <div id="removed" class="alert alert-danger" role="alert"<?=(isset($removed) ? ' data-removed="1"' : null); ?>>Removed</div>
    <div id="expired" class="alert alert-danger" role="alert"<?=(isset($expired) ? ' data-expired="1"' : null); ?>>Session Expired</div>
    <div id="failed" class="alert alert-danger" role="alert"<?=(isset($failed) ? ' data-failed="1"' : null); ?>>Login Failed</div>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/jquery-2.2.3.min.js"></script>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/bootstrap.min.js"></script>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/jax.5.0.0.min.js"></script>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/phire.js"></script>
</body>

</html>