    </div>
<!-- Footer //-->
    <footer class="footer">
        <div class="text-muted"><a href="http://www.phirecms.org/" target="_blank"><?=$application_title; ?></a> v<?=$phireVersion; ?>. &copy; 2009-<?=date('Y'); ?> <a href="http://www.nolainteractive.com/" target="_blank">NOLA Interactive</a>. All Rights Reserved.</div>
    </footer>
    <div id="installed" class="alert alert-info" role="alert"<?=(isset($installed) ? ' data-installed="1"' : null); ?>>Installation Complete</div>
    <div id="saved" class="alert alert-success" role="alert"<?=(isset($saved) ? ' data-saved="1"' : null); ?>>Saved</div>
    <div id="removed" class="alert alert-danger" role="alert"<?=(isset($removed) ? ' data-removed="1"' : null); ?>>Removed</div>
    <div id="expired" class="alert alert-danger" role="alert"<?=(isset($expired) ? ' data-expired="1"' : null); ?>>Session Expired</div>
    <div id="failed" class="alert alert-danger" role="alert"<?=(isset($failed) ? ' data-failed="1"' : null); ?>>Login Failed</div>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/jquery-3.1.1.min.js"></script>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/bootstrap.min.js"></script>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/jax.5.5.0.min.js"></script>
<script src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/phire.js"></script>
</body>

</html>