<!DOCTYPE html>
<html>

<head>

    <title>Phire CMS : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<?php if (count($assets['js']) > 0): ?>
<?php foreach ($assets['js'] as $js): ?>
    <script type="text/javascript" src="<?=$js; ?>"></script>
<?php endforeach; ?>
<?php endif; ?>

    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
<?php if (count($assets['css']) > 0): ?>
<?php foreach ($assets['css'] as $css): ?>
    <link type="text/css" rel="stylesheet" href="<?=$css; ?>" />
<?php endforeach; ?>
<?php endif; ?>

    <link rel="shortcut icon" href="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/img/phire-icon.png" type="image/png" />

</head>

<body>
<?php if (isset($user)): ?>
<div id="container">
    <header>
        <a class="logo" href="<?=BASE_PATH . (APP_URI != '') ? APP_URI : '/'; ?>">Home</a>
        <nav id="header-nav">
            <nav>
                Logged in as: <a href="<?=BASE_PATH . APP_URI; ?>/profile"><?=$user->username; ?></a>
                <nav>
                    <nav><a href="<?=BASE_PATH . APP_URI; ?>/profile">Profile</a></nav>
                    <nav><a href="<?=BASE_PATH . APP_URI; ?>/unsubscribe">Unsubscribe</a></nav>
                    <nav><a href="<?=BASE_PATH . APP_URI; ?>/logout">Logout</a></nav>
                </nav>
            </nav>
        </nav>
    </header>
<?=$phireNav; ?>
    <div id="content">
<?php endif; ?>
