<!DOCTYPE html>
<html>

<head>

    <title><?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <script type="text/javascript" src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/jax.4.0.0a.min.js"></script>
    <script type="text/javascript" src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/jax.form.min.js"></script>
    <script type="text/javascript" src="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/js/phire.js"></script>

    <link type="text/css" rel="stylesheet" href="<?=BASE_PATH . CONTENT_PATH; ?>/assets/phire/css/phire.css" />

</head>

<body>
<?php if (isset($user)): ?>
    <p><strong><a href="<?=BASE_PATH . APP_URI; ?>/profile"><?=$user->username; ?></a></strong> | <a href="<?=BASE_PATH . APP_URI; ?>">Home</a> | <a href="<?=BASE_PATH . APP_URI . '/logout'; ?>">Logout</a></p>
<?=$phireNav; ?>
<?php endif; ?>
