<?php include __DIR__ . '/header.phtml'; ?>

<?php if (isset($sideNav)): ?>
    <div class="static-sidebar">
<?=$sideNav; ?>
    </div>
    <div class="static-main">
<?php endif; ?>
        <div class="col-md-12">
            <h1 class="dashboard-header"><?=$title; ?></h1>
        </div>

        <div class="col-md-9">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th colspan="2">Recent Modules</th>
                </tr>
                </thead>
                <tbody>
<?php if (count($modules) > 0): ?>
<?php foreach ($modules as $module): ?>
                <tr>
                    <td><?=$module->name; ?></td>
                    <td><?=($module->active) ? 'Active' : 'Not Active'; ?></td>
                </tr>
<?php endforeach; ?>
<?php else: ?>
                <tr>
                    <td>
                        <p style="padding: 10px 15px 2px 15px;">There are currently no modules installed.</p>
                    </td>
                </tr>
<?php endif; ?>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <table class="table">
                <thead>
                <tr>
                    <th colspan="2">System Overview</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><strong>Phire CMS:</strong></td>
                    <td><?=$phireVersion; ?></td>
                </tr>
                <tr>
                    <td><strong>OS:</strong></td>
                    <td><?=PHP_OS; ?></td>
                </tr>
                <tr>
                    <td><strong>Server:</strong></td>
                    <td><?=(isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : ''); ?></td>
                </tr>
                <tr>
                    <td><strong>Database:</strong></td>
                    <td><?=$database; ?> (<?=$dbVersion; ?>)</td>
                </tr>
                <tr>
                    <td><strong>PHP:</strong></td>
                    <td><?=PHP_VERSION; ?></td>
                </tr>
                </tbody>
            </table>
        </div>
<?php if (isset($sideNav)): ?>
    </div>
<?php endif; ?>
<?php include __DIR__ . '/footer.phtml'; ?>