<?php include __DIR__ . '/header.phtml'; ?>

        <div class="col-md-12">
            <h1 class="dashboard-header"><?=$title; ?></h1>
        </div>

        <div class="col-md-9">
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Header</th>
                    <th>Header</th>
                    <th>Header</th>
                    <th>Header</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1001</td>
                    <td>Lorem</td>
                    <td>ipsum</td>
                    <td>dolor</td>
                    <td>sit</td>
                </tr>
                <tr>
                    <td>1002</td>
                    <td>amet</td>
                    <td>consectetur</td>
                    <td>adipiscing</td>
                    <td>elit</td>
                </tr>
                <tr>
                    <td>1003</td>
                    <td>Integer</td>
                    <td>nec</td>
                    <td>odio</td>
                    <td>Praesent</td>
                </tr>
                <tr>
                    <td>1004</td>
                    <td>libero</td>
                    <td>Sed</td>
                    <td>cursus</td>
                    <td>ante</td>
                </tr>
                <tr>
                    <td>1005</td>
                    <td>dapibus</td>
                    <td>diam</td>
                    <td>Sed</td>
                    <td>nisi</td>
                </tr>
                <tr>
                    <td>1006</td>
                    <td>Nulla</td>
                    <td>quis</td>
                    <td>sem</td>
                    <td>at</td>
                </tr>
                </tbody>
            </table>

            <h2 class="sub-header">Recent Modules</h2>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Version</th>
                    <th>Active</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>1001</td>
                    <td>phire-content</td>
                    <td>2.0</td>
                    <td>Yes</td>
                </tr>
                <tr>
                    <td>1002</td>
                    <td>phire-fields</td>
                    <td>2.0</td>
                    <td>Yes</td>
                </tr>
                <tr>
                    <td>1003</td>
                    <td>phire-navigation</td>
                    <td>2.0</td>
                    <td>Yes</td>
                </tr>
                <tr>
                    <td>1004</td>
                    <td>phire-templates</td>
                    <td>2.0</td>
                    <td>Yes</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <table class="table">
                <thead>
                <tr>
                    <th colspan="2">System Overview</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><strong>Version:</strong></td>
                    <td><?=\Phire\Module::VERSION; ?></td>
                </tr>
                <tr>
                    <td><strong>OS:</strong></td>
                    <td><?=PHP_OS; ?></td>
                </tr>
                <tr>
                    <td><strong>Server:</strong></td>
                    <td><?=(isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : ''); ?></td>
                </tr>
                <tr>
                    <td><strong>Database:</strong></td>
                    <td><?=$database; ?> (<?=$dbVersion; ?>)</td>
                </tr>
                <tr>
                    <td><strong>PHP:</strong></td>
                    <td><?=PHP_VERSION; ?></td>
                </tr>
                </tbody>
            </table>
        </div>

<?php include __DIR__ . '/footer.phtml'; ?>