<?php include $phireHeader; ?>
    <h1 class="config-header"><?=$title; ?></h1>
    <form id="config-form" method="post" action="<?=$phireUri; ?>/config">
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr><th colspan="2">&nbsp;</th></tr>
<?php foreach($overview as $setting => $value): ?>
            <tr>
                <td style="width: 25%;"><strong><?=ucwords(str_replace(['_', 'php'], [' ', 'PHP'], $setting)); ?></strong></td><td><?=(!empty($value) ? $value : '&nbsp;'); ?></td>
            </tr>
<?php endforeach; ?>
            <tr><th colspan="2">&nbsp;</th></tr>
            <tr class="no-background">
                <td class="no-background">
                    <strong>Date &amp; Time Format</strong>
                </td>
                <td class="no-background">
<?php
$wasChecked = false;
foreach($config['datetime_formats'] as $datetime):
    if ($config['datetime_format'] == $datetime):
        $checked    = 'checked="checked" ';
        $wasChecked = true;
    else:
        $checked    = '';
    endif;
?>
                    <div class="datetime-format"><input type="radio" name="datetime_format" id="datetime_format" onclick="phire.customDatetime('<?=$phireUri; ?>');" <?=$checked; ?>value="<?=$datetime; ?>" /> <span class="radio-block-span"><?=date($datetime); ?></span></div>
<?php endforeach; ?>
                    <div class="datetime-format">
                        <input type="radio" name="datetime_format" id="datetime_format8" onclick="phire.customDatetime('<?=$phireUri; ?>');" <?=((!$wasChecked) ? 'checked="checked" ' : ''); ?>value="<?=((!$wasChecked) ? $config['datetime_format'] : ''); ?>" />
                        <input type="text" name="datetime_format_custom" id="datetime_format_custom" onkeyup="phire.customDatetime('<?=$phireUri; ?>')" value="<?=((!$wasChecked) ? $config['datetime_format'] : ''); ?>" size="10" />
                        <span id="datetime-custom"><?=((!$wasChecked) ? '(' . date($config['datetime_format']) . ')' : ''); ?></span>
                    </div>
                </td>
            </tr>
            <tr class="no-background">
                <td class="no-background">
                    <strong>Pagination</strong>
                </td>
                <td class="no-background">
                    <input type="text" name="pagination" id="pagination" size="3" value="<?=$config['pagination']; ?>" />
                </td>
            </tr>
            <tr class="no-background">
                <td class="no-background">
                    <strong>System Theme</strong>
                </td>
                <td class="no-background">
                    <select name="system_theme" id="system_theme">
<?php
$wasSelected = false;
foreach($config['system_themes'] as $system_theme):
if ($config['system_theme'] == $system_theme):
    $selected    = ' selected="selected"';
    $wasSelected = true;
else:
    $selected = '';
endif;
?>
                        <option value="<?=$system_theme; ?>"<?=$selected; ?>><?=$system_theme; ?></option>
<?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </table>
        <div id="form-footer"><input type="submit" name="submit" class="save-btn" value="Save" /></div>
    </form>
<?php include $phireFooter; ?>
