#!/bin/bash
#
# Phire CMS 2.0 BASH CLI script
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"
CYG_PATH="$( which cygpath 2> /dev/null )"

if [ "$CYG_PATH" != "" ]; then
    SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\phire.php $@"
    SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
else
    SCRIPT_PATH="$SCRIPT_DIR/phire.php $@"
fi

TAR="$(which tar 2> /dev/null)"
ZIP="$(which zip 2> /dev/null)"

PH_CLI_ROOT=../..
PH_APP_PATH=
DB_CLI=
DB_CLI_DUMP=
DB_CLI_PARAMS=
DB_CLI_DUMP_PARAMS=
DB_DUMP_NAME=
DB_INTERFACE=
DB_TYPE=
DB_NAME=
DB_USER=
DB_PASS=
DB_HOST=
TIMESTAMP=$(date +%Y-%m-%d_%H-%M)

PH_APP_PATH=`cat "$PH_CLI_ROOT/config.php" | grep APP_PATH`
PH_APP_PATH=${PH_APP_PATH:20}
POS=`expr index "$PH_APP_PATH" "'"`
let "POS-=1"
PH_APP_PATH=${PH_APP_PATH:0:$POS}

DB_INTERFACE=`cat "$PH_CLI_ROOT/config.php" | grep DB_INTERFACE`
DB_INTERFACE=${DB_INTERFACE:24}
POS=`expr index "$DB_INTERFACE" "'"`
let "POS-=1"
DB_INTERFACE=${DB_INTERFACE:0:$POS}

DB_TYPE=`cat "$PH_CLI_ROOT/config.php" | grep DB_TYPE`
DB_TYPE=${DB_TYPE:19}
POS=`expr index "$DB_TYPE" "'"`
let "POS-=1"
DB_TYPE=${DB_TYPE:0:$POS}

DB_NAME=`cat "$PH_CLI_ROOT/config.php" | grep DB_NAME`
DB_NAME=${DB_NAME:19}
POS=`expr index "$DB_NAME" "'"`
let "POS-=1"
DB_NAME=${DB_NAME:0:$POS}

DB_USER=`cat "$PH_CLI_ROOT/config.php" | grep DB_USER`
DB_USER=${DB_USER:19}
POS=`expr index "$DB_USER" "'"`
let "POS-=1"
DB_USER=${DB_USER:0:$POS}

DB_PASS=`cat "$PH_CLI_ROOT/config.php" | grep DB_PASS`
DB_PASS=${DB_PASS:19}
POS=`expr index "$DB_PASS" "'"`
let "POS-=1"
DB_PASS=${DB_PASS:0:$POS}

DB_HOST=`cat "$PH_CLI_ROOT/config.php" | grep DB_HOST`
DB_HOST=${DB_HOST:19}
POS=`expr index "$DB_HOST" "'"`
let "POS-=1"
DB_HOST=${DB_HOST:0:$POS}

if [ "$DB_INTERFACE" = "Mysqli" ] || [ "$DB_TYPE" = "mysql" ]; then
    DB_CLI=`which mysql 2> /dev/null`
    DB_CLI_DUMP=`which mysqldump 2> /dev/null`
    DB_CLI_PARAMS="--database=$DB_NAME --user=$DB_USER --password=$DB_PASS --host=$DB_HOST"
    DB_CLI_DUMP_PARAMS="--user=$DB_USER --password=$DB_PASS --host=$DB_HOST $DB_NAME > $DB_NAME""_$TIMESTAMP.mysql.sql"
    DB_DUMP_NAME="$DB_NAME"_"$TIMESTAMP".mysql.sql

elif [ "$DB_INTERFACE" = "Pgsql" ] || [ "$DB_TYPE" = "pgsql" ]; then
    DB_CLI=`which psql 2> /dev/null`
    DB_CLI_DUMP=`which pg_dump 2> /dev/null`
    DB_CLI_PARAMS="--dbname=$DB_NAME --username=$DB_USER"
    DB_CLI_DUMP_PARAMS="--username=$DB_USER $DB_NAME > $DB_NAME""_$TIMESTAMP.pgsql.sql"
    DB_DUMP_NAME="$DB_NAME"_"$TIMESTAMP".pgsql.sql
elif [ "$DB_INTERFACE" = "Sqlite" ] || [ "$DB_TYPE" = "sqlite" ]; then
    DB_NAME=${DB_NAME:10}
    DB_CLI=`which sqlite3 2> /dev/null`
    DB_CLI_DUMP=`which sqlite3 2> /dev/null`
    DB_CLI_PARAMS="$PH_CLI_ROOT$DB_NAME"
    DB_CLI_DUMP_PARAMS="$PH_CLI_ROOT$DB_NAME .dump > phirecms_$TIMESTAMP.sqlite.sql"
    DB_DUMP_NAME=phirecms_"$TIMESTAMP".sqlite.sql
fi

DB_CLI=${DB_CLI// /\\ }
DB_CLI_DUMP=${DB_CLI_DUMP// /\\ }

if [ "$1" = "sql" ]; then
    if [ "$DB_INTERFACE" != "" ]; then
        if [ "$2" = "cli" ]; then
            if [ "$DB_CLI" != "" ]; then
                eval "$DB_CLI $DB_CLI_PARAMS"
            else
                echo -e "\n  That database CLI client was not found.\n"
            fi
        elif [ "$2" = "dump" ]; then
            if [ "$DB_CLI_DUMP" != "" ]; then
                echo -e "\n  Dumping Phire CMS 2 Database..."
                eval "$DB_CLI_DUMP $DB_CLI_DUMP_PARAMS"
                echo -e "  Done!\n"
            else
                echo -e "\n  That database CLI dump client was not found.\n"
            fi
        fi
    else
        echo -e "\nPhire CMS 2 CLI"
        echo -e "===============\n"
        echo -e "  Phire CMS 2 does not appear to be installed. Please check the config file or install the application."
    fi
elif [ "$1" = "archive" ]; then
    echo -e "\nPhire CMS 2 CLI"
    echo -e "===============\n"
    if [ "$DB_CLI_DUMP" = "" ]; then
        echo -e "  That database CLI dump client was not found.\n"
    elif [ "$TAR" = "" ] && [ "$ZIP" = "" ]; then
        echo -e "  Neither the TAR or ZIP utilities were found.\n"
    else
        echo -e "  Archiving the Phire CMS 2 installation..."
        eval "$DB_CLI_DUMP $DB_CLI_DUMP_PARAMS"
        if [ "$TAR" != "" ]; then
            "$TAR" -cvzpf "phirecms_$TIMESTAMP.tar.gz" $PH_CLI_ROOT/.htaccess $PH_CLI_ROOT/*
        else
            "$ZIP" -r -v "phirecms_$TIMESTAMP.zip" $PH_CLI_ROOT/.htaccess $PH_CLI_ROOT/*
        fi
        rm "$DB_DUMP_NAME"
        echo -e "  Done!\n"
    fi
else
    php $SCRIPT_PATH
    if [ "$1" = "install" ]; then
        if [ "$CYG_PATH" != "" ]; then
            SCRIPT_PATH="$( cygpath -w $SCRIPT_DIR )\\phire.php post"
            SCRIPT_PATH=${SCRIPT_PATH//\\/\/}
        else
            SCRIPT_PATH="$SCRIPT_DIR/phire.php post"
        fi
        php $SCRIPT_PATH
    fi

    if [ -d "$PH_CLI_ROOT/phire-cms-new" ]; then
        if [ "$CYG_PATH" = "" ]; then
            mv "$PH_CLI_ROOT$PH_APP_PATH" "$PH_CLI_ROOT$PH_APP_PATH-$(date +%s)"
            mv "$PH_CLI_ROOT/phire-cms-new" "$PH_CLI_ROOT$PH_APP_PATH"

            if [ -f "$PH_CLI_ROOT$PH_APP_PATH/vendor/Phire/data/update.php" ]; then
                php "$PH_CLI_ROOT$PH_APP_PATH/vendor/Phire/data/update.php"
            fi
        else
           if [ -f "$PH_CLI_ROOT/phire-cms-new/vendor/Phire/data/update.php" ]; then
               php "$PH_CLI_ROOT/phire-cms-new/vendor/Phire/data/update.php"
           fi
           echo -e "  For the Windows OS, you will have to manually rename the new system folder '/phire-cms-new'"
           echo -e "  to the correct application path, due to file and folder permission restrictions.\n"
        fi


    fi
fi

