<!DOCTYPE html>
<html>

<head>

    <title><?=$systemTitle; ?> : <?=$title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link type="image/png" rel="shortcut icon" href="<?=$contentPath; ?>/assets/phire/img/phire-icon.png"  />
    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700,700italic" />
    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:400,400italic,700,700italic" />
<?php if (count($assets['css']['link']) > 0): ?>
<?php foreach ($assets['css']['link'] as $css): ?>
    <link type="text/css" rel="stylesheet" href="<?=$css; ?>" />
<?php endforeach; ?>
<?php endif; ?>

<?php if (count($assets['css']['import']) > 0): ?>
    <style type="text/css">
<?php foreach ($assets['css']['import'] as $css): ?>
        @import url('<?=$css; ?>');
<?php endforeach; ?>
    </style>
<?php endif; ?>

<?php if (count($assets['js']) > 0): ?>
<?php foreach ($assets['js'] as $js): ?>
    <script type="text/javascript" src="<?=$js; ?>"></script>
<?php endforeach; ?>
<?php endif; ?>

</head>

<body>
<?php if (isset($user)): ?>
<div id="container">
    <header>
        <a class="logo" href="<?=(($phireUri != '') ? $phireUri : '/'); ?>">Home</a>
        <nav id="header-nav">
            <nav>
                Logged in as: <a href="<?=$phireUri; ?>/profile"><?=$user->username; ?></a>
                <nav>
<?php if ($acl->isAllowed($user->role, 'profile')): ?>
                    <nav><a href="<?=$phireUri; ?>/profile">Profile</a></nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'unsubscribe')): ?>
                    <nav><a href="<?=$phireUri; ?>/unsubscribe">Unsubscribe</a></nav>
<?php endif; ?>
                    <nav><a href="<?=$phireUri; ?>/logout">Logout</a></nav>
                </nav>
            </nav>
            <nav>
                <a title="Logout" href="<?=$phireUri; ?>/logout">Logout</a>
            </nav>
        </nav>
    </header>
<?=$phireNav; ?>
    <div id="content">
<?php endif; ?>
