        <div class="dashboard-right-column">
<?php if ($acl->isAllowed($user->role, 'dashboard')): ?>
            <table class="dashboard-table" cellspacing="0" cellpadding="0" border="0">
                <tr>
                    <th colspan="2">
                        System Overview
                    </th>
                </tr>
<?php foreach ($overview as $key => $value): ?>
<?php if ((stripos($key, 'path') === false) && (stripos($key, 'root') === false)): ?>
                <tr>
                    <td><strong><?=(ucwords(str_replace(array('_', 'php'), array(' ', 'PHP'), $key))); ?>:</strong></td>
                    <td><?=$value; ?><?php if (($key == 'version') && (version_compare($value, $phire_update_version) < 0)):
echo ' (<a class="normal-link" href="' . $phireUri . '/update">Update to ' . $phire_update_version . '</a>)';
endif; ?></td>
                </tr>
<?php endif; ?>
<?php endforeach; ?>
            </table>
<?php endif; ?>
        </div>
