<?php include $phireHeader; ?>
<div id="login">
<?=$form; ?>
    <div id="forgot"><a href="<?=$phireUri; ?>/forgot">Forgot?</a></div>
</div>
<footer id="login-footer">
    <?=$systemTitle; ?>. &copy; 2009-<?=date('Y'); ?> <a href="http://www.nolainteractive.com/" target="_blank">NOLA Interactive, LLC</a>. All Rights Reserved.
</footer>
<?php if (isset($_GET['installed'])): ?>
<div id="installed">Installation Successful</div>
<?php endif; ?>
<?php include $phireFooter; ?>
