<?php include $phireHeader; ?>
        <h1 class="update-header"><?=$title; ?></h1>
<?php if (isset($complete)): ?>
        <h3 class="required">Update completed successfully!</h3>
        <p>You have updated to Phire version <strong class="required"><?=$version; ?></strong>.</p>
<?php else: ?>
        <h3>You have chosen to update Phire CMS to version <strong class="required"><?=$phire_update_version; ?></strong></h3>
        <p class="warning">Please back up all of your files and your database before proceeding.</p>
<?php if ($form !== false): ?>
        <p>One-click updating was not detected. You must provide the FTP information below in order to begin the update:</p>
<?=$form; ?>
<?php else: ?>
        <p style="padding: 0 0 25px 0;">One-click updating has been detected. Once you click the update button below, the update process will begin.</p>
        <a class="update-btn" href="<?=$phireUri; ?>/update?update=1">Update</a>
<?php endif; ?>
        <p style="padding: 25px 0 0 0; clear: both;">If you have trouble with the update, you can attempt a manual update by <a class="normal-link" href="<?=$url; ?>">downloading the update file here</a>.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
