<?php include $phireHeader; ?>
        <h1 class="update-header"><?=$title; ?></h1>
        <h3>You have chosen to update Phire CMS to version <strong class="required"><?=$phire_update_version; ?></strong></h3>
        <p class="warning">Please back up all of your files and your database before proceeding.</p>
        <a class="update-btn" href="<?=$phireUri; ?>/update?update=1">Update</a>
<?php include $phireFooter; ?>
