<?php include $phireHeader; ?>
<div id="install-container">
    <div id="install">
    <h1><?=$title; ?></h1>
        <div id="register-form" style="margin-top: 25px;">
<?php if ($result): ?>
            <p style="text-align: center;">Thank you. Your account has been verified.</p>
<?php else: ?>
            <p style="text-align: center;">Sorry, your account could not be verified at this time.</p>
<?php endif; ?>
        </div>
    </div>
    <footer id="login-footer">
        <?=$systemTitle; ?>. &copy; 2009-<?=date('Y'); ?> <a href="http://www.nolainteractive.com/" target="_blank">NOLA Interactive, LLC</a>. All Rights Reserved.
    </footer>
</div>
<?php include $phireFooter; ?>
