<?php include $phireHeader; ?>
    <h1 class="users-header"><?=$title; ?></h1>
    <nav id="sub-nav">
<?php if ($acl->isAllowed($user->role, 'users', 'add')): ?>
        <nav><a href="<?=$phireUri . '/users/add'; ?>">+ Add</a></nav>
<?php endif; ?>
        <nav><a href="<?=$phireUri . '/users'; ?>">Back</a></nav>
    </nav>
<?php if (isset($form)): ?>
<?=$form; ?>
<?php else: ?>
    <form id="role-select-form" action="<?=$phireUri; ?>/users/add" method="get">
        <div><h3>Select Role</h3></div>
        <div>
            <select name="role_id" id="role_id" onchange="phire.selectUserRole(this, '<?=$phireUri; ?>');">
                <option value="0">----</option>
<?php foreach ($roles as $role): ?>
<?php if ($acl->isAllowed($user->role, 'users-of-role-' . $role->id, 'add')): ?>
                <option value="<?=$role->id; ?>"><?=$role->name; ?></option>
<?php endif; ?>
<?php endforeach; ?>
            </select>
        </div>
    </form>
<?php endif; ?>
<?php include $phireFooter; ?>
