<?php include $phireHeader; ?>
<?php if (count($roles) > 0): ?>
    <form id="asset-search-form" action="<?=$phireUri . '/users'; ?>" method="get">
        <div><input tabindex="4" type="submit" id="submit" value="Search" /></div>
        <div>
            <select tabindex="3" id="role_id" name="role_id">
                <option value="----">----</option>
<?php foreach ($roles as $id => $role): ?>
<?php if (($acl->hasResource('users-of-role-' . $id)) && ($acl->isAllowed($user->role, 'users-of-role-' . $id, 'index'))): ?>
                <option value="<?=$id; ?>"<?=(((null !== $roleId) && ($roleId == $id)) ? ' selected="selected"' : null); ?>><?=$role; ?></option>
<?php endif; ?>
<?php endforeach; ?>
            </select>
        </div>
        <div>
            <select tabindex="2" id="search_by" name="search_by">
                <option value="----">Search by</option>
                <option value="username"<?=(('username' == $searchBy) ? ' selected="selected"' : null); ?>>Username</option>
                <option value="first_name"<?=(('first_name' == $searchBy) ? ' selected="selected"' : null); ?>>First Name</option>
                <option value="last_name"<?=(('last_name' == $searchBy) ? ' selected="selected"' : null); ?>>Last Name</option>
                <option value="company"<?=(('company' == $searchBy) ? ' selected="selected"' : null); ?>>Company</option>
                <option value="title"<?=(('title' == $searchBy) ? ' selected="selected"' : null); ?>>Title</option>
                <option value="email"<?=(('email' == $searchBy) ? ' selected="selected"' : null); ?>>Email</option>
            </select>
        </div>
        <div><input tabindex="1" type="text" name="search_for" id="search_for" value="<?=((null !== $searchFor) ? $searchFor : null); ?>" placeholder="Search for" size="15" /></div>
    </form>
<?php endif; ?>
    <h1 class="users-header"><?=$title; ?><?php if (isset($roleId) && isset($roles) && isset($roles[$roleId])): ?> : <?=$roles[$roleId]; ?><?php endif; ?></h1>
<?php if (count($users) > 0): ?>
<?php if (null !== $pages): ?>
    <div class="page-links"><?=$pages; ?></div>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'users', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/users/add<?php if (null !== $roleId): ?><?='/' . $roleId; ?><?php endif; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
<?php if ($acl->isAllowed($user->role, 'users', 'process')): ?>
    <form id="users-form" action="<?=$phireUri . '/users/process'; ?>" method="post">
<?php endif; ?>
        <table class="data-table" cellpadding="0" cellspacing="0" border="0">
            <tr>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=id';?>">#</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=username';?>">Username</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=first_name';?>">First Name</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=last_name';?>">Last Name</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=company';?>">Company</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=title';?>">Title</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=email';?>">Email</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=role_name';?>">Role</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=verified';?>">Verified</a></th>
                <th><a href="<?=$phireUri . '/users' . ((null !== $roleId) ? '/' . $roleId : null) . '?sort=active';?>">Active</a></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'users', 'edit')): ?>Edit<?php else: ?>&nbsp;<?php endif; ?></th>
                <th class="text-center"><?php if ($acl->isAllowed($user->role, 'users', 'remove')): ?><input type="checkbox" name="checkall" id="checkall" value="process_users" /><?php else: ?>&nbsp;<?php endif; ?></th>
            </tr>
<?php $i = 1; ?>
<?php foreach ($users as $u): ?>
            <tr>
                <td><?=$u->id; ?></td>
                <td><?=$u->username; ?></td>
                <td><?=$u->first_name; ?></td>
                <td><?=$u->last_name; ?></td>
                <td><?=$u->company; ?></td>
                <td><?=$u->title; ?></td>
                <td><?=$u->email; ?></td>
                <td><?=(!empty($u->role_name) ? $u->role_name : '[Blocked]'); ?></td>
                <td><?=(($u->verified) ? 'Yes' : 'No'); ?></td>
                <td><?=(($u->active) ? 'Yes' : 'No'); ?></td>
<?php if (null !== $u->role_id): ?>
                <td><?php if (($acl->isAllowed($user->role, 'users', 'edit') && ($acl->isAllowed($user->role, 'users-of-role-' . $u->role_id, 'edit')))): ?><a class="edit-link" href="<?=$phireUri . '/users/edit/' . $u->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($user->id != $u->id) && ($acl->isAllowed($user->role, 'users', 'remove')) && ($acl->isAllowed($user->role, 'users-of-role-' . $u->role_id, 'remove'))): ?><input type="checkbox" name="process_users[]" id="process_users<?=$i++; ?>" value="<?=$u->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
<?php else: ?>
                <td><?php if ($acl->isAllowed($user->role, 'users', 'edit')): ?><a class="edit-link" href="<?=$phireUri . '/users/edit/' . $u->id; ?>">Edit</a><?php else: ?>&nbsp;<?php endif; ?></td>
                <td class="text-center"><?php if (($user->id != $u->id) && ($acl->isAllowed($user->role, 'users', 'remove'))): ?><input type="checkbox" name="process_users[]" id="process_users<?=$i++; ?>" value="<?=$u->id; ?>" /><?php else: ?>&nbsp;<?php endif; ?></td>
<?php endif;?>
            </tr>
<?php endforeach; ?>
        </table>
<?php if ($acl->isAllowed($user->role, 'users', 'remove')): ?>
        <div id="form-footer">
            <select id="user_process_action" name="user_process_action">
                <option value="1">Activate</option>
                <option value="0">Deactivate</option>
                <option value="-1">Remove</option>
            </select>
            <input type="hidden" name="role_id" value="<?php if (null !== $roleId): echo $roleId; else: echo '0'; endif; ?>" />
            <input type="submit" name="submit" class="process-btn" value="Process" />
        </div>
    </form>
<?php endif; ?>
<?php else: ?>
<?php if ($acl->isAllowed($user->role, 'users', 'add')): ?>
    <nav id="sub-nav">
        <nav><a href="<?=$phireUri; ?>/users/add<?php if (null !== $roleId): ?><?='/' . $roleId; ?><?php endif; ?>">+ Add</a></nav>
    </nav>
<?php endif; ?>
    <p>There are currently no users.</p>
<?php endif; ?>
<?php include $phireFooter; ?>
